version: "3"
services:
    db:
        image: mysql:8
        container_name: mapbot_db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mapbot
        volumes:
            - ./db-init/:/docker-entrypoint-initdb.d

    java:
        image: openjdk:11
        container_name: mapbot_java
        volumes:
            - java_storage:/usr/local/openjdk-11/

    bot:
        image: python:3.6
        container_name: mapbot_bot
        environment:
            - DOCKER=true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - java
        volumes:
            - java_storage:/usr/local/openjdk-11/:ro
        stdin_open: true
        tty: true

volumes:
    java_storage:
